blank_issues_enabled: false
contact_links:
  - name: Ask on Stack Overflow
    url: https://stackoverflow.com/questions/tagged/comsol
    about: If you want to figure out how to program something Comsol-related.
  - name: Ask on Reddit
    url: https://www.reddit.com/r/COMSOL
    about: If you want to ask other Comsol users for advice.
